routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => ['web']], function () {
    if (!env('INSTALLED', false)) {
        // Route::get('/', 'Install\InstallController@index');
        Route::get('/', 'Install\InstallController@index');
        Route::post('install/store', 'Install\InstallController@store');
        //Route::get('/', 'HomeController@index');
    } else {
        // Route::get('/', 'HomeController@index');
        Route::get('/', 'HomeController@index');
    }
    Route::get('home', 'HomeController@index');

    Route::auth();
// term and condition
    Route::get('termsCondition', 'HomeController@termsCondition');
// privacy policy
    Route::get('privacyPolicy', 'HomeController@privacyPolicy');


// Social github routes...
    Route::get('github', 'Auth\AuthController@redirectToProvider');
    Route::get('github/callback', 'Auth\AuthController@handleProviderCallback');

// Social facebook routes...
    Route::get('facebook', 'Auth\AuthController@redirectToProvider');
    Route::get('facebook/callback', 'Auth\AuthController@handleProviderCallback');

// Social google routes...
    Route::get('google', 'Auth\AuthController@redirectToProvider');
    Route::get('google/callback', 'Auth\AuthController@handleProviderCallback');

// Social twitter routes...
    Route::get('twitter', 'Auth\AuthController@redirectToProvider');
    Route::get('twitter/callback', 'Auth\AuthController@handleProviderCallback');

// Social linkedin routes...
    Route::get('linkedin', 'Auth\AuthController@redirectToProvider');
    Route::get('linkedin/callback', 'Auth\AuthController@handleProviderCallback');


//access without login
    Route::get('unsubscribe/{id}', 'EmailList\EmailListController@unsubscribe');

});


// set and prevent all route after login routes...
Route::group(['middleware' => ['web','install', 'auth', 'demo', 'package']], function () {

    Route::resource('oauth', 'Oauth\OauthController');
    Route::resource('theme', 'Theme\ThemeController');
        
    Route::post('config', 'Oauth\OauthController@updateSocialLogin');

    Route::get('email_settings/default_change/{id}', 'Email\EmailController@default_change');
    Route::post('email_settings', 'Email\EmailController@email_settings');
    Route::get('email/load_mail_provider/{mail_provider}', 'Email\EmailController@load_mail_provider');
    Route::post('email-testing', 'Email\EmailController@email_testing');
    Route::resource('email', 'Email\EmailController');
    Route::resource('system_settings', 'Settings\SettingsController');
    Route::get('paypal-api', 'ExternalApi\ExternalApiController@paypal_api');
    Route::post('store-paypal-api', 'ExternalApi\ExternalApiController@store_paypal_api');
    Route::get('stripe-api', 'ExternalApi\ExternalApiController@stripe_api');
    Route::post('store-stripe-api', 'ExternalApi\ExternalApiController@store_stripe_api');
    Route::resource('api', 'ExternalApi\ExternalApiController');
    Route::resource('profile', 'Profile\ProfileController');
    Route::resource('translation', 'Translation\TranslationController');
    Route::get('coupons/changed_published/{coupon}', 'Coupons\CouponsController@change_published');
    Route::resource('coupons', 'Coupons\CouponsController');
    Route::resource('ticketstatus', 'Settings\ticketstatusController');

// translation

    Route::get('lang/{locale}', function ($locale) {
        if (getenv('locale')) {
            $preCont = \Illuminate\Support\Facades\File::get(base_path() . '/.env');

            $newCont = str_replace('locale' . '=' . getenv('locale'), 'locale' . '=' . $locale, $preCont);

            \Illuminate\Support\Facades\File::put(base_path() . '/.env', $newCont);

        } else {
            \Illuminate\Support\Facades\File::append(base_path() . '/.env', "\nlocale=$locale");
        }
        return redirect()->back();
    });

// insert translation
    Route::post('insertLang', 'Translation\TranslationController@insertLang');
// update translation
    Route::get('updateLanguage/{id}', 'Translation\TranslationController@updateLanguage');
    // privacy
    Route::resource('privacy', 'Terms\TermsController');
    Route::any('storeTerms', 'Terms\TermsController@storeTerms');
    Route::get('backupDownload', 'DatabaseBackupController@backupDownload');

    // cron
    Route::resource('cron', 'Cron\CronController');
});


Route::group(['middleware' => ['web', 'auth', 'package']], function(){
    Route::resource('departments', 'Department\DepartmentController');
    Route::resource('frontend', 'FrontEnd\FrontEndController');

    Route::any('save-email', 'EmailList\EmailListController@save_email');
    Route::any('loadMedia', 'Media\MediaController@loadMedia');
    Route::any('update_email_info', 'EmailList\EmailListController@update_email_info');
    Route::any('email-delete/{emailList_id}', 'EmailList\EmailListController@email_delete');

    Route::resource('history', 'EmailHistory\EmailHistoryController');
    Route::get('tickets/attchment-download/{file_name}', 'Tickets\TicketsController@attachment_download');
    Route::get('tickets/change_status/{ticket_id}/{status_id}', 'Tickets\TicketsController@change_status');
    Route::get('tickets/comment_delete/{ticket_comment}', 'Tickets\TicketsController@comment_delete');
    Route::post('tickets/comment_save', 'Tickets\TicketsController@comment_save');
    Route::resource('tickets', 'Tickets\TicketsController');
    Route::get('purchase-history', 'EmailHistory\EmailHistoryController@purchase_history');
    Route::any('sent-email-list/{email_history_id}', 'EmailHistory\EmailHistoryController@sent_email_list');
    Route::get('clearHistory', 'EmailHistory\EmailHistoryController@clearHistory');

    Route::resource('email-list', 'EmailList\EmailListController');
    Route::post('email-list/save-group', 'EmailList\EmailListController@save_group');
    Route::any('real-email/{checker}/{id}', 'EmailList\EmailListController@real_email');
    Route::any('delete-invalid-email/{checker}/{id}', 'EmailList\EmailListController@delete_invalid_email');
    Route::any('load-template', 'MessageList\MessageListController@load_template');
//    Route::resource('message-list', 'MessageList\MessageListController');
    Route::post('upload_template', 'Template\TemplateController@upload_template');
    Route::resource('faq-setting', 'Faq\FaqController');
    Route::resource('template', 'Template\TemplateController');
    Route::resource('htmlTemplate', 'Template\htmlTemplate');
    Route::get('build/{column}', 'Template\htmlTemplate@buildTemplate');
    Route::resource('newsletter', 'Newsletter\NewsletterController');
    Route::resource('send-mail', 'SendMail\SendMailController');
    Route::get('send-mail/group_detail/{id}', 'SendMail\SendMailController@group_detail')->name('get-group-detail');
    Route::resource('media', 'Media\MediaController');


    Route::get('download_sample', 'HomeController@download_sample');
    //physical address
    Route::resource('address', 'Address\AddressController');

    // blacklist
    Route::resource('email_blacklist', 'Blacklist\blacklistController');
    Route::resource('word_blacklist', 'Blacklist\blacklistController');
    Route::resource('domain_blacklist', 'Blacklist\blacklistController');
    Route::resource('ip', 'Blacklist\blacklistController');
    Route::resource('attachments', 'Attachment\AttachmentController');

});

Route::group(['middleware' => ['web']], function(){
    Route::any('subscribe/{api_key?}/{group_id?}', 'Api\ApiController@subscribe');
    Route::get('link-open/{email_sent_list_id}/{email}', 'EmailHistory\EmailHistoryController@link_open');
    Route::any('email-open/{email_sent_list_id}/{email}', 'EmailHistory\EmailHistoryController@email_open');
//    pricing
    Route::resource('pricing', 'Pricing\PricingController');
//package

    Route::get('pay', 'Paypal\PaypalController@pay');
    Route::post('payment', 'Package\PackageController@payment');
    Route::get('order/{package}', 'Package\PackageController@order');
    Route::resource('package', 'Package\PackageController');
    Route::get('faq/search', 'Faq\FaqController@search');
    Route::get('faq', 'Faq\FaqController@faq_list');


});

Route::get('env_value/{value}', function ($value) {
    return $value."=".env($value);
});

resources/views/app.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>

<style>
/*loader css*/
.loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #3498db;
  border-bottom: 16px solid #3498db;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
.float {
    position: fixed;
    width: 60px;
    height: 60px;
    bottom: 17px;
    right: 20px;
    /* background-color: #0C9; */
    color: #FFF;
    border-radius: 50px;
    text-align: center;
    box-shadow: 2px 2px 3px #999;
}


.my-float {
    margin-top: 20px;
}
</style>

@include('partials.htmlheader')

<body class="skin-{!! configValue('sidebar_theme') ? configValue('sidebar_theme'):'red-light'!!} sidebar-mini">
    <!-- for loader spinner not used have to remove style -->
<div class="wrapper" id="body_content" style="opacity: 0.5">

    @include('partials.mainheader')

    @include('partials.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @include('partials.contentheader')

        <!-- Main content -->
        <section class="content">

            <?php $alert_type = ''; $msg = ''; ?>
            @if (Session::has('success_msg'))
            <?php $alert_type = 'success';
            $msg = Session::get('success_msg');
            Session::forget('success_msg');
            ?>
            @elseif(Session::has('error_msg'))
            <?php $alert_type = 'error';
            $msg = Session::pull('error_msg');
            ?>
            @elseif(Session::has('info_msg'))
            <?php $alert_type = 'info';
            $msg = Session::pull('info_msg');
            ?>
            @elseif(Session::has('warning_msg'))
            <?php $alert_type = 'warning';
            $msg = Session::pull('warning_msg');
            ?>
            @else
            <?php $alert_type = '';
            $msg = '';
            ?>
            @endif
            <!-- Your Page Content Here -->
            @yield('main-content')
        </section><!-- /.content -->
        <a href="{{route('send-mail.index')}}" class="float btn-primary">
            <i class="fa fa-plus fa-2x my-float"></i>
        </a>
    </div><!-- /.content-wrapper -->

    @include('partials.controlsidebar')

    @include('partials.footer')

</div><!-- ./wrapper -->

<!-- for loader spinner not used have to remove the below div -->
<div class="loader" style="position: fixed;
     left: 50%;
     top: 40%;
     display: block;
     z-index: 1800;
     height: 64px;
     width: 64px;">
</div>

@include('partials.scripts')

<!-- Hotjar Tracking Code for http://email-marketing.xcoder.io -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:1049623,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

<script>
    //loading spinner start
    var $loading = $('.loader');

    $(window).bind("load", function () {
        $('#body_content').css('opacity', '1.0');
        $loading.hide();
    });


    $(document)
      .ajaxStart(function () {
        $('#body_content').css('opacity', '0.5');
        $loading.show();
      })
      .ajaxStop(function () {
        $('#body_content').css('opacity', '1.0');
        $loading.hide();
      });
      // end loading spinner


    $(function () {
        var alert_type = '<?php echo $alert_type; ?>';
        var msg = '<?php echo $msg; ?>';
        if((alert_type != '') && (msg != '')){
            Command: toastr[alert_type](msg);
            alert_type = '';
            msg = '';
        }
    });

</script>
</body>
</html>

resources/views/autopost.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>autoposter</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
        <link href="https://unpkg.com/vuetify/dist/vuetify.min.css" rel="stylesheet">

        <!-- Styles -->
    </head>
    <body>
        <div id="app">
            
        </div>
        <script src="{{ asset('js/app.js') }}"></script>
    </body>
</html>

resources/views/old-getting-start.blade.php
<?/*<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="email marketing web application">
        <meta name="author" content="xCoder.io">
        <title>Email Marketing</title>
        <!-- core CSS -->
        <link href="{{ asset('plugins/pricing/css/bootstrap.min.css') }}" rel="stylesheet">
        <!-- toastr -->
        <link href="{{ asset('/css/toastr.min.css') }}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('plugins/pricing/css/font-awesome.min.css') }}" rel="stylesheet">
        <link href="{{ asset('plugins/pricing/css/animate.min.css') }}" rel="stylesheet">
        <link href="{{ asset('plugins/pricing/css/owl.carousel.css') }}" rel="stylesheet">
        <link href="{{ asset('plugins/pricing/css/owl.transitions.css') }}" rel="stylesheet">
        <link href="{{ asset('plugins/pricing/css/prettyPhoto.css') }}" rel="stylesheet">
        <link href="{{ asset('plugins/pricing/css/main.css') }}" rel="stylesheet">
        <link href="{{ asset('plugins/pricing/css/responsive.css') }}" rel="stylesheet">
        <!--[if lt IE 9]>
        <script src="{{ asset('plugins/pricing/js/html5shiv.js') }}"></script>
        <script src="{{ asset('plugins/pricing/js/respond.min.js') }}"></script>
        <![endif]-->
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{ asset('plugins/pricing/images/ico/apple-touch-icon-114-precomposed.png') }}">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{ asset('plugins/pricing/images/ico/apple-touch-icon-72-precomposed.png') }}">
        <link rel="apple-touch-icon-precomposed" href="{{ asset('plugins/pricing/images/ico/apple-touch-icon-57-precomposed.png') }}">
    </head><!--/head-->

    <body id="home" class="homepage">

    <header id="header">
        <nav id="main-menu" class="navbar navbar-default navbar-fixed-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{{ url('/') }}">
                    <!--<img style="height: 65px;" class="img-responsive" src="{{ asset('plugins/pricing/images/xCoder.jpeg') }}" alt="logo"> -->
                    <!-- <h3>Postman</h3> -->
                    <img style="height: 65px;" class="img-responsive" src="{{ asset('plugins/pricing/images/Mailpokes.png') }}" alt="logo">

                    </a>

                </div>

                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="scroll active"><a href="{{ url('/') }}">Home</a></li>
                       <!--  <li class="scroll"><a href="#features">Features</a></li>
                        <li class="scroll"><a href="#portfolio">Portfolio</a></li> -->
                        <li class="scroll"><a href="#about">About</a></li>
                      <!--   <li class="scroll"><a href="#meet-team">Team</a></li> -->
                        <li class="scroll"><a href="#pricing">Pricing</a></li>
                        <li class="scroll"><a href="#get-in-touch">Contact</a></li>
                      <!--   <li class="scroll"><a href="{{ url('faq') }}">{{ trans('common.faq') }}</a></li> -->
                        <li class="scroll"><a href="{{url('login')}}">{{ trans('auth.log_in') }}</a></li>
                        <li class="scroll"><a href="{{url('register')}}">{{ trans('auth.Register') }}</a></li>
                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->
    </header><!--/header-->


    <section id="pricing">
        <div class="">
            <div class="section-header">
                <h2 class="section-title text-center wow fadeInDown">Pricing Table</h2>
                <p class="text-center wow fadeInDown">Choose the package you prefer from below</p>
            </div>

            <div class="row">
                @foreach($packages as $key => $package)
                    <div class="col-sm-6 col-md-3">
                        <div class="wow zoomIn" data-wow-duration="400ms" data-wow-delay="0ms">
                            <ul class="pricing">
                                <li class="plan-header">
                                    <div class="price-duration">
                                        <span class="price">
                                            ${{ $package->price }}
                                        </span>
                                        <span class="duration">
                                            {{ $package->validity . ' ' .trans('common.days') }}
                                        </span>
                                    </div>

                                    <div class="plan-name">
                                        {{ $package->name }}
                                    </div>
                                </li>
                                <li>{{ trans('common.limit') }} <strong>{{ $package->limit }}</strong> {{ trans('common.emails') }}</li>
                                <li>{{ trans('common.limit') }} <strong>{{ $package->user_limit }}</strong> {{ trans('common.user(s)') }}</li>
                                <li>{{ trans('common.validity') }} <strong>{{ $package->validity }}</strong> {{ trans('common.days') }}</li>
                                <li class="plan-purchase"><a class="btn btn-primary" href="{{ url('package'. '/'. $package->id )}}" onclick="order(this, event, '{{ "redeem_coupon_$package->id" }}')">ORDER NOW</a></li>

                                <a href="#" onclick="show_redeem_coupon(this, event, '{{ "redeem_coupon_$package->id" }}')">{{ trans('common.redeem'). ' ' .trans('common.coupon') }}</a>
                                
                                <input class="form-control" name='code' id="redeem_coupon_{{ $package->id }}" style="display: none">
                            </ul>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section><!--/#pricing-->


    @foreach($frontEnds as $frontEnd)
        {!! $frontEnd->description !!}
    @endforeach

    <script>
        function show_redeem_coupon(that, e, field_id) {
            e.preventDefault();

            if($('#'+field_id).is(':visible')) {
                $(that).text("{{ trans('common.redeem'). ' ' .trans('common.coupon') }}");
                $('#'+field_id).hide('slow');
            } else {
                $(that).text("{{ trans('common.remove'). ' ' .trans('common.coupon') }}");
                $('#'+field_id).show('slow');
            }
        }

        function order(that, e, field_id) {
            e.preventDefault();
            var code = $('#'+ field_id).val();
            var url = $(that).attr('href');
            if(code) {
                url = url + '?code=' + code;
            } 

            window.location.href = url;
        }

    </script>


                <?php $alert_type = ''; $msg = ''; ?>
                @if (Session::has('success_msg'))
                <?php $alert_type = 'success';
                $msg = Session::get('success_msg');
                Session::forget('success_msg');
                ?>
                @elseif(Session::has('error_msg'))
                <?php $alert_type = 'error';
                $msg = Session::pull('error_msg');
                ?>
                @elseif(Session::has('info_msg'))
                <?php $alert_type = 'info';
                $msg = Session::pull('info_msg');
                ?>
                @elseif(Session::has('warning_msg'))
                <?php $alert_type = 'warning';
                $msg = Session::pull('warning_msg');
                ?>
                @else
                <?php $alert_type = '';
                $msg = '';
                ?>
                @endif


    <script src="{{ asset('plugins/pricing/js/jquery.js') }}"></script>
    <script src="{{ asset('plugins/pricing/js/bootstrap.min.js') }}"></script>
    <!-- Bootstrap toastr -->
    <script src="{{ asset('/js/toastr.min.js') }}" type="text/javascript"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="{{ asset('plugins/pricing/js/owl.carousel.min.js') }}"></script>
    <script src="{{ asset('plugins/pricing/js/mousescroll.js') }}"></script>
    <script src="{{ asset('plugins/pricing/js/smoothscroll.js') }}"></script>
    <script src="{{ asset('plugins/pricing/js/jquery.prettyPhoto.js') }}"></script>
    <script src="{{ asset('plugins/pricing/js/jquery.isotope.min.js') }}"></script>
    <script src="{{ asset('plugins/pricing/js/jquery.inview.min.js') }}"></script>
    <script src="{{ asset('plugins/pricing/js/wow.min.js') }}"></script>
    <script src="{{ asset('plugins/pricing/js/main.js') }}"></script>

    <script>
        $(function () {
            var alert_type = '<?php echo $alert_type; ?>';
            var msg = '<?php echo $msg; ?>';
            if((alert_type != '') && (msg != '')){
                Command: toastr[alert_type](msg);
                alert_type = '';
                msg = '';
            }
        });
    </script>

    </body>
    </html>
*/?>

resources/views/testmail.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
        
</head>
<body>
    
    <div class="container">
        @if($emailTemplate != '')
            <div>
                {!! $emailTemplate !!}
            </div>
        @endif
    </div>

    <h5>From: admin@xcoder.io</h5>
</body>
</html>